- name: install httpd package
  hosts: webservers
  become: yes
  tasks:
    - name: install packages
      yum:
        name: "httpd"
        state : "present"

    - name: start Apache server
      service:
        name: "httpd"

        
              